name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Env
        run: pip list

      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt
          # echo "MLFLOW_TRACKING_URI=${{ vars.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

      - name: Run MLflow Project and Capture RUN_ID
        id: run_mlflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local 2>&1 | tee output.log
          
          RUN_ID=$(grep "MLFLOW_RUN_ID=" output.log | cut -d'=' -f2)
          
          if [ -z "$RUN_ID" ]; then
            RUN_ID=$(grep -oE "[a-f0-9]{32}" output.log | head -n1)
          fi
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Validated RUN_ID: $RUN_ID"

      - name: Upload ML artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: MLProject

      - name: Build Docker Model
        run: |
          MODEL_PATH="MLProject/mlruns/0/${{ env.RUN_ID }}/artifacts/model"
          
          if [ ! -d "$MODEL_PATH" ]; then
            echo "Model artifacts not found at $MODEL_PATH"
            exit 1
          fi

          mlflow models build-docker \
            --model-uri "$MODEL_PATH" \
            --name "diamond-price-model"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag diamond-price-model ${{ vars.DOCKERHUB_USERNAME }}/diamond-price-model:latest

      - name: Push Docker Image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/diamond-price-model:latest
